package com.claudetest.matchtiles.audio

import android.content.Context
import android.media.AudioAttributes
import android.media.MediaPlayer
import android.media.SoundPool
import androidx.compose.runtime.staticCompositionLocalOf
import com.claudetest.matchtiles.R

/** Every one-shot sound the game can make. All of them are generated by tools/make_audio.py. */
enum class Sfx { Tap, Button, Shuffle, Match, Miss, Clear, Over, Win }

/**
 * Anything that can make a noise, so composables can ask for a sound without holding a
 * player. [LocalAudio] hands out [SilentAudio] by default, which keeps previews quiet.
 */
interface AudioController {
    fun play(sfx: Sfx)
}

object SilentAudio : AudioController {
    override fun play(sfx: Sfx) = Unit
}

val LocalAudio = staticCompositionLocalOf<AudioController> { SilentAudio }

/**
 * Owns the game's audio: a [SoundPool] for the short interface sounds and a looping
 * [MediaPlayer] for the background music.
 *
 * The two are switched independently, matching the two options in the settings sheet. The
 * music also stops whenever the app is not in the foreground, so it never plays on top of
 * whatever the player switched to.
 */
class GameAudio(context: Context) : AudioController {

    private val app = context.applicationContext

    private val pool = SoundPool.Builder()
        .setMaxStreams(MAX_STREAMS)
        .setAudioAttributes(
            AudioAttributes.Builder()
                .setUsage(AudioAttributes.USAGE_GAME)
                .setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION)
                .build()
        )
        .build()

    // Loading is asynchronous, but every clip is a few kilobytes and this happens behind
    // the splash screen, so they are ready long before anything can be tapped.
    private val clips: Map<Sfx, Int> = mapOf(
        Sfx.Tap to pool.load(app, R.raw.sfx_tap, 1),
        Sfx.Button to pool.load(app, R.raw.sfx_button, 1),
        Sfx.Shuffle to pool.load(app, R.raw.sfx_shuffle, 1),
        Sfx.Match to pool.load(app, R.raw.sfx_match, 1),
        Sfx.Miss to pool.load(app, R.raw.sfx_miss, 1),
        Sfx.Clear to pool.load(app, R.raw.sfx_clear, 1),
        Sfx.Over to pool.load(app, R.raw.sfx_over, 1),
        Sfx.Win to pool.load(app, R.raw.sfx_win, 1),
    )

    private var player: MediaPlayer? = null
    private var musicWanted = false
    private var foreground = true

    /** The "tap sounds" switch. */
    var soundEnabled: Boolean = true

    override fun play(sfx: Sfx) {
        if (!soundEnabled) return
        val clip = clips[sfx] ?: return
        pool.play(clip, SFX_VOLUME, SFX_VOLUME, 1, 0, 1f)
    }

    /** The "background music" switch. The loop is only created once it is actually wanted. */
    fun setMusicEnabled(enabled: Boolean) {
        musicWanted = enabled
        sync()
    }

    fun onForeground() {
        foreground = true
        sync()
    }

    fun onBackground() {
        foreground = false
        sync()
    }

    fun release() {
        player?.release()
        player = null
        pool.release()
    }

    private fun sync() {
        if (musicWanted && foreground) {
            val loop = player ?: MediaPlayer.create(app, R.raw.bgm_loop)?.apply {
                isLooping = true
                setVolume(MUSIC_VOLUME, MUSIC_VOLUME)
            }?.also { player = it } ?: return
            if (!loop.isPlaying) loop.start()
        } else {
            player?.takeIf { it.isPlaying }?.pause()
        }
    }

    private companion object {
        const val MAX_STREAMS = 4
        const val SFX_VOLUME = 0.9f
        /** Music sits well under the effects; it is background, not the show. */
        const val MUSIC_VOLUME = 0.35f
    }
}
